name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 6'  # Every Saturday 6 AM
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest, nightly]
    runs-on: ubuntu-latest
    
    steps:
      - name: Download source
        uses: actions/checkout@v2
      
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      
      - name: Install shards
        run: shards update --ignore-crystal-version
      
      - name: Run specs
        #run: crystal spec --order=random
        run: make test

      - name: Check formatting
        run: crystal tool format --check

      - name: Static code analysis
        run: crystal bin/ameba.cr 